sdk_error_map = {
    0: "SADP_NOERROR 没有错误",
    2001: "SADP_ALLOC_RESOURCE_ERROR 资源分配错误",
    2002: "SADP_NOT_START_ERROR 未启动",
    2003: "SADP_NO_ADAPTER_ERROR 无网卡",
    2004: "SADP_GET_ADAPTER_FAIL_ERROR 获取网卡信息失败",
    2005: "SADP_PARAMETER_ERROR 参数错误",
    2006: "SADP_OPEN_ADAPTER_FAIL_ERROR 打开网卡失败",
    2007: "SADP_SEND_PACKET_FAIL_ERROR 发送数据失败",
    2008: "SADP_SYSTEM_CALL_ERROR 系统接口调用失败",
    2009: "SADP_DENY_OR_TIMEOUT_ERROR 设备拒绝处理",
    2010: "SADP_NPF_INSTALL_ERROR 安装NPF服务失败",
    2011: "SADP_TIMEOUT 超时",
    2012: "SADP_CREATE_SOCKET_ERROR 创建socket失败",
    2013: "SADP_BIND_SOCKET_ERROR 绑定socket失败",
    2014: "SADP_JOIN_MULTI_CAST_ERROR 加入多播组失败",
    2015: "SADP_NETWORK_SEND_ERROR 发送出错",
    2016: "SADP_NETWORK_RECV_ERROR 接收出错",
    2017: "SADP_XML_PARSE_ERROR 多播XML解析出错",
    2018: "SADP_LOCKED 设备锁定",
    2019: "SADP_NOT_ACTIVATED 设备未激活",
    2020: "SADP_RISK_PASSWORD 风险高的密码",
    2021: "SADP_HAS_ACTIVATED 设备已激活",
    2022: "SADP_EMPTY_ENCRYPT_STRING 加密串为空",
    2023: "SADP_EXPORT_FILE_OVERDUE 导出文件超期",
    2024: "SADP_PASSWORD_ERROR 密码错误",
    2025: "SADP_LONG_SECURITY_ANSWER 安全问题答案太长",
    2026: "SADP_INVALID_GUID 无效的GUID",
    2027: "SADP_ANSWER_ERROR 答案错误",
    2028: "SADP_QUESTION_NUM_ERR 安全问题个数配置错误",
    2030: "SADP_LOAD_WPCAP_FAIL 加载Wpcap失败",
    2033: "SADP_ILLEGAL_VERIFICATION_CODE 非法验证码",
    2034: "SADP_BIND_ERROR_DEV 绑定错误的设备",
    2035: "SADP_EXTED_MAX_BIND_NUM 超过最大绑定个数",
    2036: "SADP_MAILBOX_NOT_EXIST 邮箱不存在",
    2038: "SADP_MAILBOX_NOT_SET 邮箱重置密码未设置邮箱",
    2039: "SADP_INVALID_RESET_CODE 重置密码（重置口令）错误。",
    2040: "SADP_NO_PERMISSION 没有权限： 1.Win&Linux下没有管理员权限操作网卡；2.Android IOS没有多播权限",
    2041: "SADP_GET_EXCHANGE_CODE_ERROR 获取加密用的交换码失败",
    2042: "SADP_CREATE_RSA_KEY_ERROR 生成RSA公私钥失败",
    2043: "SADP_BASE64_ENCODE_ERROR BASE64编码错误",
    2044: "SADP_BASE64_DECODE_ERROR BASE64解码错误",
    2045: "SADP_AES_ENCRYPT_ERROR AES加密失败",
    2046: "SADP_PHONE_NOT_SET 手机扫码重置密码未设置安全手机",
    2047: "SADP_NOENOUGH_BUF 缓冲区长度不足",
    2048: "SADP_INVALID_SUBNET_IP 无效的网段范围，起始IP地址大于终止IP地址或者超过4096个IP地址",
}

def sdk_err_msg(err_code: int) -> str:
    return sdk_error_map.get(err_code, f"未知错误代码: {err_code}")
